### ISSUE TITLE
Lab 1 feedback

### ISSUE THREAD

**Issue by jsrc1115** [LuimarcoCarrascalDiaz/summerschoolAI#1]
1. Remember in general and more in an academic setting to include the sources of your information. (7 points)

2. (10 points)

3. (15 points)
The script is missing the prompt from your choice, also the ReAct prompt is more a CoT prompt, the more complex type of prompts usually have a lot more context and in the case of ReAct it needs to have actions and observations to setup, from the Paper summary:
"reasoning traces help the model induce, track, and update action plans as well as handle exceptions, while actions allow it to interface with external sources, such as knowledge bases or environments, to gather additional information." https://arxiv.org/abs/2210.03629

4. (10 points) You did not document the prompts or the outputs, quoting the lab text: "and document any prompts/outputs in a file
similar to previous questions."

5. (0 points) Not present in the repo.

7 + 10 + 15 + 10 + 0 = 42

**Comment by jsrc1115** [comment]
@LuimarcoCarrascalDiaz The offer to re-review the 5th point still stands but please upload the code too, you just added screenshots

**Comment by LuimarcoCarrascalDiaz** [comment]
I have uploaded the code.
Sincerely, Luimarco

Obtener Outlook para iOS<https://aka.ms/o0ukef>
________________________________
De: jsrc1115 ***@***.***>
Enviado: Thursday, July 18, 2024 8:18:32 PM
Para: LuimarcoCarrascalDiaz/summerschoolAI ***@***.***>
Cc: Luimarco Daniel Santiago Carrascal Diaz ***@***.***>; Mention ***@***.***>
Asunto: Re: [LuimarcoCarrascalDiaz/summerschoolAI] Lab 1 feedback (Issue #1)


@LuimarcoCarrascalDiaz<https://github.com/LuimarcoCarrascalDiaz> The offer to re-review the 5th point still stands but please upload the code too, you just added screenshots

**Comment by jsrc1115** [comment]
Reviewing new changes:

5. (10 points) Got half of 20 points because as I mentioned in the class and in the presentation PDF that tokens are not the same length as words https://help.openai.com/en/articles/4936856-what-are-tokens-and-how-to-count-them.

7 + 10 + 15 + 10 + 10 = 52
